### ISSUE TITLE
Select page

### ISSUE THREAD

**Issue by Farahismail** [denhartog/jquery-simple-pagination#4]
Hello,

I am using this jquery for pagination, it's great and easy to use.
But I'm having a problem with returning back to a certain page. 
Example:
- I have 5 topics in each page
- In each topic I have read more button
- Let's say I want to see a topic from the second page
- When I click on read more from a topic in the second page it will take you to a new page with more text about this topic
- What i want is when I finish reading the topic I will click on back button but it will take me to the first page and not the second page where i was before. 

How can I redirect to a specific page ?
Please help as soon as possible.

Thank you.

**Comment by denhartog** [comment]
In short, what you want to do is currently outside the scope of simple-pagination.

However, a very simple solution to your issue is to merely include `target="_blank"` in your "Read More" button link. Doing so will preserve the state of simple-pagination as your "topic" will be loaded into a new tab/window.

**Comment by Farahismail** [comment]
Thank you for replying.
Even if I put target blank for read more, there is still one problem.
There is a like button on each topic, when they like a topic it will call a php page then come back to that specific page.

**Comment by denhartog** [comment]
So, they load the topic list page with the pagination, click on read more, the topic opens in a new tab, they read/like the topic, close the topic-only tab, then return to the tab with the topic pagination. What is the problem?

**Comment by Farahismail** [comment]
They need like under each topic.
For example in the second page we have 5 topics, under each topic there is a like button.

**Comment by sudoforge** [comment]
@Farahismail You can add your desired functionality to this project. What you'll want to do is:
- On clicking "next" or "previous" (or sibling) buttons, update the user's address bar with a GET parameter, e.g. `?page=2`.
- On page load, determine whether or not `GET['page']` exists. If it does, then call `refresh_simple_pagination(page)` on your container.

**Resources**
- https://developer.mozilla.org/en-US/docs/Web/API/History_API
- http://stackoverflow.com/questions/814613/how-to-read-get-data-from-a-url-using-javascript
- https://github.com/ddenhartog/jquery-simple-pagination/blob/master/jquery-simple-pagination-plugin.js#L236

**Comment by Farahismail** [comment]
Really appreciate the help.
I tried using refresh_simple_pagination(page) but it didn't work I guess I'm doing it the wrong way. 
Let's say i added parameter ?page=2 to like button link.
it will goes to topic_like.php where it will run sql query to add the like counter in database and then I should return to the specific page number 2.
I usually use header("Location: ../topics.php"); but now i will pass back the parameter so it will be 
header("Location: ../topics.php?page=2");
In topics page if there is a page parameter then i should call refresh_simple_pagination(page).
But I don't know if it's true to just call it this way :

<script>
    refresh_simple_pagination(page);
</script>

Please advise if I'm making something wrong

**Comment by denhartog** [comment]
It sounds as of your liking process should be handled using ajax.

**Comment by Farahismail** [comment]
I have too many jqueries on this page for countdown , slider ... 
and I tried ajax for another page with tabs, it made the countdown stopped that's why I'm trying another way.

**Comment by denhartog** [comment]
Your project wouldn't happen to be live on the Internet somewhere, would it?

**Comment by Farahismail** [comment]
No it's not online yet.
I tried everything you told me, and i managed to retrieve the page number when i get back to topics page but when i call refresh_simple_pagination(pagenumber); it will not work and I get "Uncaught ReferenceError: refresh_simple_pagination is not defined" 
do you know how to call this function from topics page ?

**Comment by bddenhartog** [comment]
@Farahismail Please write a **concise** example of what you have on [gist.github.com][gist], and provide the link to your gist here.

[gist]: "https://gist.github.com"
